# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# ENV variables
ENV['MATCH_GIT_BEARER_AUTHORIZATION'] = 'ZHV5bmI5MjpnaHBfQTJqM2NYU2JVb3RHQ1F4dUtIY2ZvM0JaNHJmMVZFM0wwZ0hX'

default_platform(:ios)

platform :ios do
  desc "Get development certificates & profiles"
  lane :cert_dev do
    match(type: "development", app_identifier: "com.agileops.blueprint")
  end
end
